---
- name: (agent5) Create Datadog agent config directory
  file:
    dest: /etc/dd-agent
    state: directory

- name: (agent5) Create main Datadog agent configuration file
  template:
    src: datadog.conf.j2
    dest: /etc/dd-agent/datadog.conf
    owner: "{{ datadog_user }}"
    group: "{{ datadog_group }}"
  notify: restart datadog-agent

- debug: 'msg="[DEPRECATION NOTICE] Using `datadog_process_checks` is deprecated, use `process` under `datadog_checks` instead"'
  when: datadog_process_checks is defined


- name: Ensure datadog-agent is running
  service: name=datadog-agent state=started enabled={{datadog_service_enabled}}
  when: datadog_enabled

- name: Ensure datadog-agent is not running
  service: name=datadog-agent state=stopped enabled={{datadog_service_enabled}}
  when: not datadog_enabled


- name: (agent5) Create a configuration file for each Datadog check
  template:
    src: checks.yaml.j2
    dest: "/etc/dd-agent/conf.d/{{ item }}.yaml"
    owner: "{{ datadog_user }}"
    group: "{{ datadog_group }}"
  with_items: "{{ datadog_checks|list }}"
  notify: restart datadog-agent






- name: various checks
  template:
    src: "{{item}}.j2"
    dest: "/etc/dd-agent/conf.d/{{ item }}"
    owner: '{{ datadog_user }}'
    group: '{{ datadog_group }}'
  with_items: '{{ datadog_manual_checks }}'
  notify: restart datadog-agent