---
- include_tasks: pkg-debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: pkg-redhat.yml
  when: ansible_os_family == "RedHat"

- import_tasks: dogstream.yml
  when: datadog_dogstreams
  tags: "datadog:dogstream"

- include: pkg-suse.yml
  when: ansible_os_family == "Suse"

- include: agent5.yml
  when: datadog_agent5

- include: agent6.yml
  when: not datadog_agent5
