---
- include_tasks: pkg-debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: pkg-redhat.yml
  when: ansible_os_family == "RedHat"


- import_tasks: dogstream.yml
  when: datadog_dogstreams
  tags: "datadog:dogstream"

- import_tasks: agent5.yml
  when: not datadog_agent6

- import_tasks: agent6.yml
  when: datadog_agent6
